coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "e2e/**"
  - "**/*_test.go"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
